#!/usr/bin/env sh

FIFO="$XDG_RUNTIME_DIR/sandbar"
[ -e "$FIFO" ] && rm -f "$FIFO"
mkfifo "$FIFO"

while cat "$FIFO"; do :; done | sandbar \
	-font "Agave Nerd Font:size=18" \
	-active-fg-color "#ffffff" \
	-active-bg-color "#d55d0e" \
	-inactive-fg-color "#ffffff" \
	-inactive-bg-color "#282828" \
	-title-fg-color "#ffffff" \
	-title-bg-color "#d55d0e"
